//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторного создания кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManager
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="HotelManager", ConfigurationName="HotelManager.HotelManagerPortType")]
    public interface HotelManagerPortType
    {
        
        // CODEGEN: Параметр "productID" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "Microsoft.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="HotelManager#HotelManager:getProducts", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        HotelManager.getProductsResponse getProducts(HotelManager.getProductsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="HotelManager#HotelManager:getProducts", ReplyAction="*")]
        System.Threading.Tasks.Task<HotelManager.getProductsResponse> getProductsAsync(HotelManager.getProductsRequest request);
        
        // CODEGEN: Параметр "moneyStoreID" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "Microsoft.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="HotelManager#HotelManager:getMoneyStoresList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        HotelManager.getMoneyStoresListResponse getMoneyStoresList(HotelManager.getMoneyStoresListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="HotelManager#HotelManager:getMoneyStoresList", ReplyAction="*")]
        System.Threading.Tasks.Task<HotelManager.getMoneyStoresListResponse> getMoneyStoresListAsync(HotelManager.getMoneyStoresListRequest request);
        
        // CODEGEN: Параметр "userName" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "Microsoft.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="HotelManager#HotelManager:getUserSettings", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        HotelManager.getUserSettingsResponse getUserSettings(HotelManager.getUserSettingsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="HotelManager#HotelManager:getUserSettings", ReplyAction="*")]
        System.Threading.Tasks.Task<HotelManager.getUserSettingsResponse> getUserSettingsAsync(HotelManager.getUserSettingsRequest request);
        
        // CODEGEN: Параметр "organizationID" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "Microsoft.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="HotelManager#HotelManager:getOrganizationsList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        HotelManager.getOrganizationsListResponse getOrganizationsList(HotelManager.getOrganizationsListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="HotelManager#HotelManager:getOrganizationsList", ReplyAction="*")]
        System.Threading.Tasks.Task<HotelManager.getOrganizationsListResponse> getOrganizationsListAsync(HotelManager.getOrganizationsListRequest request);
        
        // CODEGEN: Параметр "documentID" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "Microsoft.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="HotelManager#HotelManager:getDocuments", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        HotelManager.getDocumentsResponse getDocuments(HotelManager.getDocumentsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="HotelManager#HotelManager:getDocuments", ReplyAction="*")]
        System.Threading.Tasks.Task<HotelManager.getDocumentsResponse> getDocumentsAsync(HotelManager.getDocumentsRequest request);
        
        // CODEGEN: Параметр "storeID" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "Microsoft.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="HotelManager#HotelManager:getStoresList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        HotelManager.getStoresListResponse getStoresList(HotelManager.getStoresListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="HotelManager#HotelManager:getStoresList", ReplyAction="*")]
        System.Threading.Tasks.Task<HotelManager.getStoresListResponse> getStoresListAsync(HotelManager.getStoresListRequest request);
        
        // CODEGEN: Параметр "clientID" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "Microsoft.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="HotelManager#HotelManager:getClients", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        HotelManager.getClientsResponse getClients(HotelManager.getClientsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="HotelManager#HotelManager:getClients", ReplyAction="*")]
        System.Threading.Tasks.Task<HotelManager.getClientsResponse> getClientsAsync(HotelManager.getClientsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="HotelManager#HotelManager:getUsers", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        HotelManager.UsersList getUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="HotelManager#HotelManager:getUsers", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<HotelManager.UsersList> getUsersAsync();
        
        // CODEGEN: Параметр "agreementId" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "Microsoft.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="HotelManager#HotelManager:getAgrementsList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        HotelManager.getAgrementsListResponse getAgrementsList(HotelManager.getAgrementsListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="HotelManager#HotelManager:getAgrementsList", ReplyAction="*")]
        System.Threading.Tasks.Task<HotelManager.getAgrementsListResponse> getAgrementsListAsync(HotelManager.getAgrementsListRequest request);
        
        // CODEGEN: Параметр "return" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "Microsoft.Xml.Serialization.XmlArrayAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="HotelManager#HotelManager:setCharacteristicEasyMSRoomId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        HotelManager.setCharacteristicEasyMSRoomIdResponse setCharacteristicEasyMSRoomId(HotelManager.setCharacteristicEasyMSRoomIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="HotelManager#HotelManager:setCharacteristicEasyMSRoomId", ReplyAction="*")]
        System.Threading.Tasks.Task<HotelManager.setCharacteristicEasyMSRoomIdResponse> setCharacteristicEasyMSRoomIdAsync(HotelManager.setCharacteristicEasyMSRoomIdRequest request);
        
        // CODEGEN: Параметр "return" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "Microsoft.Xml.Serialization.XmlArrayItemAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="HotelManager#HotelManager:setDocuments", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        HotelManager.setDocumentsResponse setDocuments(HotelManager.setDocumentsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="HotelManager#HotelManager:setDocuments", ReplyAction="*")]
        System.Threading.Tasks.Task<HotelManager.setDocumentsResponse> setDocumentsAsync(HotelManager.setDocumentsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="HotelManager#HotelManager:getMoneyStoreBalance", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        HotelManager.MoneyStoreBalance getMoneyStoreBalance(string moenyStoreId);
        
        [System.ServiceModel.OperationContractAttribute(Action="HotelManager#HotelManager:getMoneyStoreBalance", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<HotelManager.MoneyStoreBalance> getMoneyStoreBalanceAsync(string moenyStoreId);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.hotel-manager.org")]
    public partial class ProductsList
    {
        
        private Product[] dataField;
        
        private string errorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("data", Order=0)]
        public Product[] data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string error
        {
            get
            {
                return this.errorField;
            }
            set
            {
                this.errorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.hotel-manager.org")]
    public partial class Product
    {
        
        private string idField;
        
        private string nameField;
        
        private string skuField;
        
        private bool isDeletedField;
        
        private System.Nullable<float> priceField;
        
        private Unit[] unitsField;
        
        private Characteristic[] characteristicsField;
        
        private string eANField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string Sku
        {
            get
            {
                return this.skuField;
            }
            set
            {
                this.skuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool IsDeleted
        {
            get
            {
                return this.isDeletedField;
            }
            set
            {
                this.isDeletedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<float> Price
        {
            get
            {
                return this.priceField;
            }
            set
            {
                this.priceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Units", Order=5)]
        public Unit[] Units
        {
            get
            {
                return this.unitsField;
            }
            set
            {
                this.unitsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Characteristics", Order=6)]
        public Characteristic[] Characteristics
        {
            get
            {
                return this.characteristicsField;
            }
            set
            {
                this.characteristicsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string EAN
        {
            get
            {
                return this.eANField;
            }
            set
            {
                this.eANField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.hotel-manager.org")]
    public partial class Unit
    {
        
        private string idField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.hotel-manager.org")]
    public partial class MoneyStoreBalance
    {
        
        private double currentBalanceField;
        
        private double dayBalancePositiveField;
        
        private double dayBalanceNegativeField;
        
        private Error[] errorsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public double currentBalance
        {
            get
            {
                return this.currentBalanceField;
            }
            set
            {
                this.currentBalanceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public double dayBalancePositive
        {
            get
            {
                return this.dayBalancePositiveField;
            }
            set
            {
                this.dayBalancePositiveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public double dayBalanceNegative
        {
            get
            {
                return this.dayBalanceNegativeField;
            }
            set
            {
                this.dayBalanceNegativeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("errors", Order=3)]
        public Error[] errors
        {
            get
            {
                return this.errorsField;
            }
            set
            {
                this.errorsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.hotel-manager.org")]
    public partial class Error
    {
        
        private int errorCodeField;
        
        private string errorDescriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int errorCode
        {
            get
            {
                return this.errorCodeField;
            }
            set
            {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string errorDescription
        {
            get
            {
                return this.errorDescriptionField;
            }
            set
            {
                this.errorDescriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.hotel-manager.org")]
    public partial class Agreement
    {
        
        private string idField;
        
        private string nameField;
        
        private DocumentType typeField;
        
        private string clientIdField;
        
        private bool isDeletedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public DocumentType Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ClientId
        {
            get
            {
                return this.clientIdField;
            }
            set
            {
                this.clientIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public bool IsDeleted
        {
            get
            {
                return this.isDeletedField;
            }
            set
            {
                this.isDeletedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.hotel-manager.org")]
    public enum DocumentType
    {
        
        /// <remarks/>
        Sell,
        
        /// <remarks/>
        Buy,
        
        /// <remarks/>
        ReturnFromClient,
        
        /// <remarks/>
        ReturnToClient,
        
        /// <remarks/>
        MoneyGet,
        
        /// <remarks/>
        MoneyPut,
        
        /// <remarks/>
        MoneyReturnFromClient,
        
        /// <remarks/>
        MoneyReturnToClient,
        
        /// <remarks/>
        MoneyTransfer,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.hotel-manager.org")]
    public partial class AgreementsList
    {
        
        private Agreement[] dataField;
        
        private string errorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("data", Order=0)]
        public Agreement[] data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string error
        {
            get
            {
                return this.errorField;
            }
            set
            {
                this.errorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.hotel-manager.org")]
    public partial class User
    {
        
        private string idField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.hotel-manager.org")]
    public partial class UsersList
    {
        
        private User[] dataField;
        
        private string errorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("data", Order=0)]
        public User[] data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string error
        {
            get
            {
                return this.errorField;
            }
            set
            {
                this.errorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.hotel-manager.org")]
    public partial class Client
    {
        
        private string idField;
        
        private string nameField;
        
        private string[] agreementsIdField;
        
        private bool isDeletedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("data", IsNullable=false)]
        public string[] AgreementsId
        {
            get
            {
                return this.agreementsIdField;
            }
            set
            {
                this.agreementsIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool IsDeleted
        {
            get
            {
                return this.isDeletedField;
            }
            set
            {
                this.isDeletedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.hotel-manager.org")]
    public partial class ClientsList
    {
        
        private Client[] dataField;
        
        private string errorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("data", Order=0)]
        public Client[] data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string error
        {
            get
            {
                return this.errorField;
            }
            set
            {
                this.errorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.hotel-manager.org")]
    public partial class Store
    {
        
        private string idField;
        
        private string nameField;
        
        private bool isDeletedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool IsDeleted
        {
            get
            {
                return this.isDeletedField;
            }
            set
            {
                this.isDeletedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.hotel-manager.org")]
    public partial class StoresList
    {
        
        private Store[] dataField;
        
        private string errorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("data", Order=0)]
        public Store[] data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string error
        {
            get
            {
                return this.errorField;
            }
            set
            {
                this.errorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.hotel-manager.org")]
    public partial class ProductItem
    {
        
        private string productIdField;
        
        private float quantityField;
        
        private float priceField;
        
        private string unitIdField;
        
        private string characteristicIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ProductId
        {
            get
            {
                return this.productIdField;
            }
            set
            {
                this.productIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public float Quantity
        {
            get
            {
                return this.quantityField;
            }
            set
            {
                this.quantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public float Price
        {
            get
            {
                return this.priceField;
            }
            set
            {
                this.priceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string UnitId
        {
            get
            {
                return this.unitIdField;
            }
            set
            {
                this.unitIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string CharacteristicId
        {
            get
            {
                return this.characteristicIdField;
            }
            set
            {
                this.characteristicIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.hotel-manager.org")]
    public partial class Document
    {
        
        private string idField;
        
        private string organizationIdField;
        
        private string clientIdField;
        
        private string storeIdField;
        
        private string userIdField;
        
        private System.Nullable<System.DateTime> dateField;
        
        private string commentField;
        
        private bool isActiveField;
        
        private bool isDeletedField;
        
        private string parentDocumentIdField;
        
        private string[] childDocumentsIdField;
        
        private DocumentType documentTypeField;
        
        private string agreementIdField;
        
        private ProductItem[] productItemsField;
        
        private string moneyStoreIdField;
        
        private string moneyStoreToIdField;
        
        private float sumField;
        
        private string easyMSBookingIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string OrganizationId
        {
            get
            {
                return this.organizationIdField;
            }
            set
            {
                this.organizationIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string ClientId
        {
            get
            {
                return this.clientIdField;
            }
            set
            {
                this.clientIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string StoreId
        {
            get
            {
                return this.storeIdField;
            }
            set
            {
                this.storeIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string UserId
        {
            get
            {
                return this.userIdField;
            }
            set
            {
                this.userIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<System.DateTime> Date
        {
            get
            {
                return this.dateField;
            }
            set
            {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string Comment
        {
            get
            {
                return this.commentField;
            }
            set
            {
                this.commentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public bool IsActive
        {
            get
            {
                return this.isActiveField;
            }
            set
            {
                this.isActiveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public bool IsDeleted
        {
            get
            {
                return this.isDeletedField;
            }
            set
            {
                this.isDeletedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public string ParentDocumentId
        {
            get
            {
                return this.parentDocumentIdField;
            }
            set
            {
                this.parentDocumentIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=10)]
        [System.Xml.Serialization.XmlArrayItemAttribute("data", IsNullable=false)]
        public string[] ChildDocumentsId
        {
            get
            {
                return this.childDocumentsIdField;
            }
            set
            {
                this.childDocumentsIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public DocumentType DocumentType
        {
            get
            {
                return this.documentTypeField;
            }
            set
            {
                this.documentTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string AgreementId
        {
            get
            {
                return this.agreementIdField;
            }
            set
            {
                this.agreementIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ProductItems", Order=13)]
        public ProductItem[] ProductItems
        {
            get
            {
                return this.productItemsField;
            }
            set
            {
                this.productItemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=14)]
        public string MoneyStoreId
        {
            get
            {
                return this.moneyStoreIdField;
            }
            set
            {
                this.moneyStoreIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=15)]
        public string MoneyStoreToId
        {
            get
            {
                return this.moneyStoreToIdField;
            }
            set
            {
                this.moneyStoreToIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public float Sum
        {
            get
            {
                return this.sumField;
            }
            set
            {
                this.sumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=17)]
        public string easyMSBookingId
        {
            get
            {
                return this.easyMSBookingIdField;
            }
            set
            {
                this.easyMSBookingIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.hotel-manager.org")]
    public partial class DocumentsList
    {
        
        private Document[] dataField;
        
        private string errorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("data", Order=0)]
        public Document[] data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string error
        {
            get
            {
                return this.errorField;
            }
            set
            {
                this.errorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.hotel-manager.org")]
    public partial class Organization
    {
        
        private string idField;
        
        private string nameField;
        
        private bool isDeletedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool IsDeleted
        {
            get
            {
                return this.isDeletedField;
            }
            set
            {
                this.isDeletedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.hotel-manager.org")]
    public partial class OrganizationsList
    {
        
        private Organization[] dataField;
        
        private string errorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("data", Order=0)]
        public Organization[] data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string error
        {
            get
            {
                return this.errorField;
            }
            set
            {
                this.errorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.hotel-manager.org")]
    public partial class UserSettings
    {
        
        private string userIDField;
        
        private string defaultOrganizationIdField;
        
        private string defaultStoreIdField;
        
        private string defaultMoneyStoreIdField;
        
        private string errorField;
        
        private string defaultClientIdField;
        
        private string defaultMoneyStoreCashIdField;
        
        private string defaultMoneyStoreTerminalIdField;
        
        private string defaultMoneyStoreTransferIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UserID
        {
            get
            {
                return this.userIDField;
            }
            set
            {
                this.userIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string DefaultOrganizationId
        {
            get
            {
                return this.defaultOrganizationIdField;
            }
            set
            {
                this.defaultOrganizationIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string DefaultStoreId
        {
            get
            {
                return this.defaultStoreIdField;
            }
            set
            {
                this.defaultStoreIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string DefaultMoneyStoreId
        {
            get
            {
                return this.defaultMoneyStoreIdField;
            }
            set
            {
                this.defaultMoneyStoreIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string error
        {
            get
            {
                return this.errorField;
            }
            set
            {
                this.errorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string DefaultClientId
        {
            get
            {
                return this.defaultClientIdField;
            }
            set
            {
                this.defaultClientIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string DefaultMoneyStoreCashId
        {
            get
            {
                return this.defaultMoneyStoreCashIdField;
            }
            set
            {
                this.defaultMoneyStoreCashIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string DefaultMoneyStoreTerminalId
        {
            get
            {
                return this.defaultMoneyStoreTerminalIdField;
            }
            set
            {
                this.defaultMoneyStoreTerminalIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public string DefaultMoneyStoreTransferId
        {
            get
            {
                return this.defaultMoneyStoreTransferIdField;
            }
            set
            {
                this.defaultMoneyStoreTransferIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.hotel-manager.org")]
    public partial class MoneyStore
    {
        
        private string idField;
        
        private string nameField;
        
        private string organizationIdField;
        
        private bool isDeletedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string OrganizationId
        {
            get
            {
                return this.organizationIdField;
            }
            set
            {
                this.organizationIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool IsDeleted
        {
            get
            {
                return this.isDeletedField;
            }
            set
            {
                this.isDeletedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.hotel-manager.org")]
    public partial class MoneyStoresList
    {
        
        private MoneyStore[] dataField;
        
        private string errorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("data", Order=0)]
        public MoneyStore[] data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string error
        {
            get
            {
                return this.errorField;
            }
            set
            {
                this.errorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.hotel-manager.org")]
    public partial class Characteristic
    {
        
        private string idField;
        
        private string nameField;
        
        private System.Nullable<float> priceField;
        
        private string eANField;
        
        private string easyMSRoomIdField;
        
        private bool isDeletedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<float> Price
        {
            get
            {
                return this.priceField;
            }
            set
            {
                this.priceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string EAN
        {
            get
            {
                return this.eANField;
            }
            set
            {
                this.eANField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string EasyMSRoomId
        {
            get
            {
                return this.easyMSRoomIdField;
            }
            set
            {
                this.easyMSRoomIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public bool IsDeleted
        {
            get
            {
                return this.isDeletedField;
            }
            set
            {
                this.isDeletedField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getProducts", WrapperNamespace="HotelManager", IsWrapped=true)]
    public partial class getProductsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="HotelManager", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string productID;
        
        public getProductsRequest()
        {
        }
        
        public getProductsRequest(string productID)
        {
            this.productID = productID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getProductsResponse", WrapperNamespace="HotelManager", IsWrapped=true)]
    public partial class getProductsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="HotelManager", Order=0)]
        public HotelManager.ProductsList @return;
        
        public getProductsResponse()
        {
        }
        
        public getProductsResponse(HotelManager.ProductsList @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getMoneyStoresList", WrapperNamespace="HotelManager", IsWrapped=true)]
    public partial class getMoneyStoresListRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="HotelManager", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string moneyStoreID;
        
        public getMoneyStoresListRequest()
        {
        }
        
        public getMoneyStoresListRequest(string moneyStoreID)
        {
            this.moneyStoreID = moneyStoreID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getMoneyStoresListResponse", WrapperNamespace="HotelManager", IsWrapped=true)]
    public partial class getMoneyStoresListResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="HotelManager", Order=0)]
        public HotelManager.MoneyStoresList @return;
        
        public getMoneyStoresListResponse()
        {
        }
        
        public getMoneyStoresListResponse(HotelManager.MoneyStoresList @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getUserSettings", WrapperNamespace="HotelManager", IsWrapped=true)]
    public partial class getUserSettingsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="HotelManager", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userName;
        
        public getUserSettingsRequest()
        {
        }
        
        public getUserSettingsRequest(string userName)
        {
            this.userName = userName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getUserSettingsResponse", WrapperNamespace="HotelManager", IsWrapped=true)]
    public partial class getUserSettingsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="HotelManager", Order=0)]
        public HotelManager.UserSettings @return;
        
        public getUserSettingsResponse()
        {
        }
        
        public getUserSettingsResponse(HotelManager.UserSettings @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getOrganizationsList", WrapperNamespace="HotelManager", IsWrapped=true)]
    public partial class getOrganizationsListRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="HotelManager", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string organizationID;
        
        public getOrganizationsListRequest()
        {
        }
        
        public getOrganizationsListRequest(string organizationID)
        {
            this.organizationID = organizationID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getOrganizationsListResponse", WrapperNamespace="HotelManager", IsWrapped=true)]
    public partial class getOrganizationsListResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="HotelManager", Order=0)]
        public HotelManager.OrganizationsList @return;
        
        public getOrganizationsListResponse()
        {
        }
        
        public getOrganizationsListResponse(HotelManager.OrganizationsList @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getDocuments", WrapperNamespace="HotelManager", IsWrapped=true)]
    public partial class getDocumentsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="HotelManager", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string documentID;
        
        public getDocumentsRequest()
        {
        }
        
        public getDocumentsRequest(string documentID)
        {
            this.documentID = documentID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getDocumentsResponse", WrapperNamespace="HotelManager", IsWrapped=true)]
    public partial class getDocumentsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="HotelManager", Order=0)]
        public HotelManager.DocumentsList @return;
        
        public getDocumentsResponse()
        {
        }
        
        public getDocumentsResponse(HotelManager.DocumentsList @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getStoresList", WrapperNamespace="HotelManager", IsWrapped=true)]
    public partial class getStoresListRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="HotelManager", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string storeID;
        
        public getStoresListRequest()
        {
        }
        
        public getStoresListRequest(string storeID)
        {
            this.storeID = storeID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getStoresListResponse", WrapperNamespace="HotelManager", IsWrapped=true)]
    public partial class getStoresListResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="HotelManager", Order=0)]
        public HotelManager.StoresList @return;
        
        public getStoresListResponse()
        {
        }
        
        public getStoresListResponse(HotelManager.StoresList @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getClients", WrapperNamespace="HotelManager", IsWrapped=true)]
    public partial class getClientsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="HotelManager", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string clientID;
        
        public getClientsRequest()
        {
        }
        
        public getClientsRequest(string clientID)
        {
            this.clientID = clientID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getClientsResponse", WrapperNamespace="HotelManager", IsWrapped=true)]
    public partial class getClientsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="HotelManager", Order=0)]
        public HotelManager.ClientsList @return;
        
        public getClientsResponse()
        {
        }
        
        public getClientsResponse(HotelManager.ClientsList @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAgrementsList", WrapperNamespace="HotelManager", IsWrapped=true)]
    public partial class getAgrementsListRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="HotelManager", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string agreementId;
        
        public getAgrementsListRequest()
        {
        }
        
        public getAgrementsListRequest(string agreementId)
        {
            this.agreementId = agreementId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAgrementsListResponse", WrapperNamespace="HotelManager", IsWrapped=true)]
    public partial class getAgrementsListResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="HotelManager", Order=0)]
        public HotelManager.AgreementsList @return;
        
        public getAgrementsListResponse()
        {
        }
        
        public getAgrementsListResponse(HotelManager.AgreementsList @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setCharacteristicEasyMSRoomId", WrapperNamespace="HotelManager", IsWrapped=true)]
    public partial class setCharacteristicEasyMSRoomIdRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="HotelManager", Order=0)]
        public string CharacteristicId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="HotelManager", Order=1)]
        public string EasyMSRoomId;
        
        public setCharacteristicEasyMSRoomIdRequest()
        {
        }
        
        public setCharacteristicEasyMSRoomIdRequest(string CharacteristicId, string EasyMSRoomId)
        {
            this.CharacteristicId = CharacteristicId;
            this.EasyMSRoomId = EasyMSRoomId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setCharacteristicEasyMSRoomIdResponse", WrapperNamespace="HotelManager", IsWrapped=true)]
    public partial class setCharacteristicEasyMSRoomIdResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="HotelManager", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("errors", Namespace="http://www.hotel-manager.org", IsNullable=false)]
        public HotelManager.Error[] @return;
        
        public setCharacteristicEasyMSRoomIdResponse()
        {
        }
        
        public setCharacteristicEasyMSRoomIdResponse(HotelManager.Error[] @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setDocuments", WrapperNamespace="HotelManager", IsWrapped=true)]
    public partial class setDocumentsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="HotelManager", Order=0)]
        public HotelManager.DocumentsList documents;
        
        public setDocumentsRequest()
        {
        }
        
        public setDocumentsRequest(HotelManager.DocumentsList documents)
        {
            this.documents = documents;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setDocumentsResponse", WrapperNamespace="HotelManager", IsWrapped=true)]
    public partial class setDocumentsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="HotelManager", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("errors", Namespace="http://www.hotel-manager.org", IsNullable=false)]
        public HotelManager.Error[] @return;
        
        public setDocumentsResponse()
        {
        }
        
        public setDocumentsResponse(HotelManager.Error[] @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface HotelManagerPortTypeChannel : HotelManager.HotelManagerPortType, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class HotelManagerPortTypeClient : System.ServiceModel.ClientBase<HotelManager.HotelManagerPortType>, HotelManager.HotelManagerPortType
    {
        
        /// <summary>
        /// Реализуйте этот разделяемый метод для настройки конечной точки службы.
        /// </summary>
        /// <param name="serviceEndpoint">Настраиваемая конечная точка</param>
        /// <param name="clientCredentials">Учетные данные клиента.</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public HotelManagerPortTypeClient(EndpointConfiguration endpointConfiguration) : 
                base(HotelManagerPortTypeClient.GetBindingForEndpoint(endpointConfiguration), HotelManagerPortTypeClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public HotelManagerPortTypeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(HotelManagerPortTypeClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public HotelManagerPortTypeClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(HotelManagerPortTypeClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public HotelManagerPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HotelManager.getProductsResponse HotelManager.HotelManagerPortType.getProducts(HotelManager.getProductsRequest request)
        {
            return base.Channel.getProducts(request);
        }
        
        public HotelManager.ProductsList getProducts(string productID)
        {
            HotelManager.getProductsRequest inValue = new HotelManager.getProductsRequest();
            inValue.productID = productID;
            HotelManager.getProductsResponse retVal = ((HotelManager.HotelManagerPortType)(this)).getProducts(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HotelManager.getProductsResponse> HotelManager.HotelManagerPortType.getProductsAsync(HotelManager.getProductsRequest request)
        {
            return base.Channel.getProductsAsync(request);
        }
        
        public System.Threading.Tasks.Task<HotelManager.getProductsResponse> getProductsAsync(string productID)
        {
            HotelManager.getProductsRequest inValue = new HotelManager.getProductsRequest();
            inValue.productID = productID;
            return ((HotelManager.HotelManagerPortType)(this)).getProductsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HotelManager.getMoneyStoresListResponse HotelManager.HotelManagerPortType.getMoneyStoresList(HotelManager.getMoneyStoresListRequest request)
        {
            return base.Channel.getMoneyStoresList(request);
        }
        
        public HotelManager.MoneyStoresList getMoneyStoresList(string moneyStoreID)
        {
            HotelManager.getMoneyStoresListRequest inValue = new HotelManager.getMoneyStoresListRequest();
            inValue.moneyStoreID = moneyStoreID;
            HotelManager.getMoneyStoresListResponse retVal = ((HotelManager.HotelManagerPortType)(this)).getMoneyStoresList(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HotelManager.getMoneyStoresListResponse> HotelManager.HotelManagerPortType.getMoneyStoresListAsync(HotelManager.getMoneyStoresListRequest request)
        {
            return base.Channel.getMoneyStoresListAsync(request);
        }
        
        public System.Threading.Tasks.Task<HotelManager.getMoneyStoresListResponse> getMoneyStoresListAsync(string moneyStoreID)
        {
            HotelManager.getMoneyStoresListRequest inValue = new HotelManager.getMoneyStoresListRequest();
            inValue.moneyStoreID = moneyStoreID;
            return ((HotelManager.HotelManagerPortType)(this)).getMoneyStoresListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HotelManager.getUserSettingsResponse HotelManager.HotelManagerPortType.getUserSettings(HotelManager.getUserSettingsRequest request)
        {
            return base.Channel.getUserSettings(request);
        }
        
        public HotelManager.UserSettings getUserSettings(string userName)
        {
            HotelManager.getUserSettingsRequest inValue = new HotelManager.getUserSettingsRequest();
            inValue.userName = userName;
            HotelManager.getUserSettingsResponse retVal = ((HotelManager.HotelManagerPortType)(this)).getUserSettings(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HotelManager.getUserSettingsResponse> HotelManager.HotelManagerPortType.getUserSettingsAsync(HotelManager.getUserSettingsRequest request)
        {
            return base.Channel.getUserSettingsAsync(request);
        }
        
        public System.Threading.Tasks.Task<HotelManager.getUserSettingsResponse> getUserSettingsAsync(string userName)
        {
            HotelManager.getUserSettingsRequest inValue = new HotelManager.getUserSettingsRequest();
            inValue.userName = userName;
            return ((HotelManager.HotelManagerPortType)(this)).getUserSettingsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HotelManager.getOrganizationsListResponse HotelManager.HotelManagerPortType.getOrganizationsList(HotelManager.getOrganizationsListRequest request)
        {
            return base.Channel.getOrganizationsList(request);
        }
        
        public HotelManager.OrganizationsList getOrganizationsList(string organizationID)
        {
            HotelManager.getOrganizationsListRequest inValue = new HotelManager.getOrganizationsListRequest();
            inValue.organizationID = organizationID;
            HotelManager.getOrganizationsListResponse retVal = ((HotelManager.HotelManagerPortType)(this)).getOrganizationsList(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HotelManager.getOrganizationsListResponse> HotelManager.HotelManagerPortType.getOrganizationsListAsync(HotelManager.getOrganizationsListRequest request)
        {
            return base.Channel.getOrganizationsListAsync(request);
        }
        
        public System.Threading.Tasks.Task<HotelManager.getOrganizationsListResponse> getOrganizationsListAsync(string organizationID)
        {
            HotelManager.getOrganizationsListRequest inValue = new HotelManager.getOrganizationsListRequest();
            inValue.organizationID = organizationID;
            return ((HotelManager.HotelManagerPortType)(this)).getOrganizationsListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HotelManager.getDocumentsResponse HotelManager.HotelManagerPortType.getDocuments(HotelManager.getDocumentsRequest request)
        {
            return base.Channel.getDocuments(request);
        }
        
        public HotelManager.DocumentsList getDocuments(string documentID)
        {
            HotelManager.getDocumentsRequest inValue = new HotelManager.getDocumentsRequest();
            inValue.documentID = documentID;
            HotelManager.getDocumentsResponse retVal = ((HotelManager.HotelManagerPortType)(this)).getDocuments(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HotelManager.getDocumentsResponse> HotelManager.HotelManagerPortType.getDocumentsAsync(HotelManager.getDocumentsRequest request)
        {
            return base.Channel.getDocumentsAsync(request);
        }
        
        public System.Threading.Tasks.Task<HotelManager.getDocumentsResponse> getDocumentsAsync(string documentID)
        {
            HotelManager.getDocumentsRequest inValue = new HotelManager.getDocumentsRequest();
            inValue.documentID = documentID;
            return ((HotelManager.HotelManagerPortType)(this)).getDocumentsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HotelManager.getStoresListResponse HotelManager.HotelManagerPortType.getStoresList(HotelManager.getStoresListRequest request)
        {
            return base.Channel.getStoresList(request);
        }
        
        public HotelManager.StoresList getStoresList(string storeID)
        {
            HotelManager.getStoresListRequest inValue = new HotelManager.getStoresListRequest();
            inValue.storeID = storeID;
            HotelManager.getStoresListResponse retVal = ((HotelManager.HotelManagerPortType)(this)).getStoresList(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HotelManager.getStoresListResponse> HotelManager.HotelManagerPortType.getStoresListAsync(HotelManager.getStoresListRequest request)
        {
            return base.Channel.getStoresListAsync(request);
        }
        
        public System.Threading.Tasks.Task<HotelManager.getStoresListResponse> getStoresListAsync(string storeID)
        {
            HotelManager.getStoresListRequest inValue = new HotelManager.getStoresListRequest();
            inValue.storeID = storeID;
            return ((HotelManager.HotelManagerPortType)(this)).getStoresListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HotelManager.getClientsResponse HotelManager.HotelManagerPortType.getClients(HotelManager.getClientsRequest request)
        {
            return base.Channel.getClients(request);
        }
        
        public HotelManager.ClientsList getClients(string clientID)
        {
            HotelManager.getClientsRequest inValue = new HotelManager.getClientsRequest();
            inValue.clientID = clientID;
            HotelManager.getClientsResponse retVal = ((HotelManager.HotelManagerPortType)(this)).getClients(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HotelManager.getClientsResponse> HotelManager.HotelManagerPortType.getClientsAsync(HotelManager.getClientsRequest request)
        {
            return base.Channel.getClientsAsync(request);
        }
        
        public System.Threading.Tasks.Task<HotelManager.getClientsResponse> getClientsAsync(string clientID)
        {
            HotelManager.getClientsRequest inValue = new HotelManager.getClientsRequest();
            inValue.clientID = clientID;
            return ((HotelManager.HotelManagerPortType)(this)).getClientsAsync(inValue);
        }
        
        public HotelManager.UsersList getUsers()
        {
            return base.Channel.getUsers();
        }
        
        public System.Threading.Tasks.Task<HotelManager.UsersList> getUsersAsync()
        {
            return base.Channel.getUsersAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HotelManager.getAgrementsListResponse HotelManager.HotelManagerPortType.getAgrementsList(HotelManager.getAgrementsListRequest request)
        {
            return base.Channel.getAgrementsList(request);
        }
        
        public HotelManager.AgreementsList getAgrementsList(string agreementId)
        {
            HotelManager.getAgrementsListRequest inValue = new HotelManager.getAgrementsListRequest();
            inValue.agreementId = agreementId;
            HotelManager.getAgrementsListResponse retVal = ((HotelManager.HotelManagerPortType)(this)).getAgrementsList(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HotelManager.getAgrementsListResponse> HotelManager.HotelManagerPortType.getAgrementsListAsync(HotelManager.getAgrementsListRequest request)
        {
            return base.Channel.getAgrementsListAsync(request);
        }
        
        public System.Threading.Tasks.Task<HotelManager.getAgrementsListResponse> getAgrementsListAsync(string agreementId)
        {
            HotelManager.getAgrementsListRequest inValue = new HotelManager.getAgrementsListRequest();
            inValue.agreementId = agreementId;
            return ((HotelManager.HotelManagerPortType)(this)).getAgrementsListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HotelManager.setCharacteristicEasyMSRoomIdResponse HotelManager.HotelManagerPortType.setCharacteristicEasyMSRoomId(HotelManager.setCharacteristicEasyMSRoomIdRequest request)
        {
            return base.Channel.setCharacteristicEasyMSRoomId(request);
        }
        
        public HotelManager.Error[] setCharacteristicEasyMSRoomId(string CharacteristicId, string EasyMSRoomId)
        {
            HotelManager.setCharacteristicEasyMSRoomIdRequest inValue = new HotelManager.setCharacteristicEasyMSRoomIdRequest();
            inValue.CharacteristicId = CharacteristicId;
            inValue.EasyMSRoomId = EasyMSRoomId;
            HotelManager.setCharacteristicEasyMSRoomIdResponse retVal = ((HotelManager.HotelManagerPortType)(this)).setCharacteristicEasyMSRoomId(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HotelManager.setCharacteristicEasyMSRoomIdResponse> HotelManager.HotelManagerPortType.setCharacteristicEasyMSRoomIdAsync(HotelManager.setCharacteristicEasyMSRoomIdRequest request)
        {
            return base.Channel.setCharacteristicEasyMSRoomIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<HotelManager.setCharacteristicEasyMSRoomIdResponse> setCharacteristicEasyMSRoomIdAsync(string CharacteristicId, string EasyMSRoomId)
        {
            HotelManager.setCharacteristicEasyMSRoomIdRequest inValue = new HotelManager.setCharacteristicEasyMSRoomIdRequest();
            inValue.CharacteristicId = CharacteristicId;
            inValue.EasyMSRoomId = EasyMSRoomId;
            return ((HotelManager.HotelManagerPortType)(this)).setCharacteristicEasyMSRoomIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HotelManager.setDocumentsResponse HotelManager.HotelManagerPortType.setDocuments(HotelManager.setDocumentsRequest request)
        {
            return base.Channel.setDocuments(request);
        }
        
        public HotelManager.Error[] setDocuments(HotelManager.DocumentsList documents)
        {
            HotelManager.setDocumentsRequest inValue = new HotelManager.setDocumentsRequest();
            inValue.documents = documents;
            HotelManager.setDocumentsResponse retVal = ((HotelManager.HotelManagerPortType)(this)).setDocuments(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HotelManager.setDocumentsResponse> HotelManager.HotelManagerPortType.setDocumentsAsync(HotelManager.setDocumentsRequest request)
        {
            return base.Channel.setDocumentsAsync(request);
        }
        
        public System.Threading.Tasks.Task<HotelManager.setDocumentsResponse> setDocumentsAsync(HotelManager.DocumentsList documents)
        {
            HotelManager.setDocumentsRequest inValue = new HotelManager.setDocumentsRequest();
            inValue.documents = documents;
            return ((HotelManager.HotelManagerPortType)(this)).setDocumentsAsync(inValue);
        }
        
        public HotelManager.MoneyStoreBalance getMoneyStoreBalance(string moenyStoreId)
        {
            return base.Channel.getMoneyStoreBalance(moenyStoreId);
        }
        
        public System.Threading.Tasks.Task<HotelManager.MoneyStoreBalance> getMoneyStoreBalanceAsync(string moenyStoreId)
        {
            return base.Channel.getMoneyStoreBalanceAsync(moenyStoreId);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.HotelManagerSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.HotelManagerSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Не удалось найти конечную точку с именем \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.HotelManagerSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://192.168.1.152/ApartmentDeveloper/ws/ws2.1cws");
            }
            if ((endpointConfiguration == EndpointConfiguration.HotelManagerSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://192.168.1.152/ApartmentDeveloper/ws/ws2.1cws");
            }
            throw new System.InvalidOperationException(string.Format("Не удалось найти конечную точку с именем \"{0}\".", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            HotelManagerSoap,
            
            HotelManagerSoap12,
        }
    }
}
