//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторного создания кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManager
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="HotelManager", ConfigurationName="HotelManager.HotelManagerPortType")]
    public interface HotelManagerPortType
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="HotelManager#HotelManager:getHello", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string getHello();
        
        [System.ServiceModel.OperationContractAttribute(Action="HotelManager#HotelManager:getHello", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getHelloAsync();
        
        // CODEGEN: Параметр "productID" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "Microsoft.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="HotelManager#HotelManager:getProducts", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        HotelManager.getProductsResponse getProducts(HotelManager.getProductsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="HotelManager#HotelManager:getProducts", ReplyAction="*")]
        System.Threading.Tasks.Task<HotelManager.getProductsResponse> getProductsAsync(HotelManager.getProductsRequest request);
        
        // CODEGEN: Параметр "moneyStoreID" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "Microsoft.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="HotelManager#HotelManager:getMoneyStoresList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        HotelManager.getMoneyStoresListResponse getMoneyStoresList(HotelManager.getMoneyStoresListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="HotelManager#HotelManager:getMoneyStoresList", ReplyAction="*")]
        System.Threading.Tasks.Task<HotelManager.getMoneyStoresListResponse> getMoneyStoresListAsync(HotelManager.getMoneyStoresListRequest request);
        
        // CODEGEN: Параметр "userName" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "Microsoft.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="HotelManager#HotelManager:getUserSettings", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        HotelManager.getUserSettingsResponse getUserSettings(HotelManager.getUserSettingsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="HotelManager#HotelManager:getUserSettings", ReplyAction="*")]
        System.Threading.Tasks.Task<HotelManager.getUserSettingsResponse> getUserSettingsAsync(HotelManager.getUserSettingsRequest request);
        
        // CODEGEN: Параметр "organizationID" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "Microsoft.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="HotelManager#HotelManager:getOrganizationsList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        HotelManager.getOrganizationsListResponse getOrganizationsList(HotelManager.getOrganizationsListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="HotelManager#HotelManager:getOrganizationsList", ReplyAction="*")]
        System.Threading.Tasks.Task<HotelManager.getOrganizationsListResponse> getOrganizationsListAsync(HotelManager.getOrganizationsListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="HotelManager#HotelManager:getSales", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        HotelManager.SalesList getSales();
        
        [System.ServiceModel.OperationContractAttribute(Action="HotelManager#HotelManager:getSales", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<HotelManager.SalesList> getSalesAsync();
        
        // CODEGEN: Параметр "storeID" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "Microsoft.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="HotelManager#HotelManager:getStoresList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        HotelManager.getStoresListResponse getStoresList(HotelManager.getStoresListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="HotelManager#HotelManager:getStoresList", ReplyAction="*")]
        System.Threading.Tasks.Task<HotelManager.getStoresListResponse> getStoresListAsync(HotelManager.getStoresListRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.hotel-manager.org")]
    public partial class ProductsList
    {
        
        private Product[] dataField;
        
        private string errorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("data", Order=0)]
        public Product[] data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string error
        {
            get
            {
                return this.errorField;
            }
            set
            {
                this.errorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.hotel-manager.org")]
    public partial class Product
    {
        
        private string idField;
        
        private string nameField;
        
        private string skuField;
        
        private bool isDeletedField;
        
        private System.Nullable<float> priceField;
        
        private Unit[] unitsField;
        
        private Characteristic[] characteristicsField;
        
        private string eANField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string Sku
        {
            get
            {
                return this.skuField;
            }
            set
            {
                this.skuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool IsDeleted
        {
            get
            {
                return this.isDeletedField;
            }
            set
            {
                this.isDeletedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<float> Price
        {
            get
            {
                return this.priceField;
            }
            set
            {
                this.priceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Units", Order=5)]
        public Unit[] Units
        {
            get
            {
                return this.unitsField;
            }
            set
            {
                this.unitsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Characteristics", Order=6)]
        public Characteristic[] Characteristics
        {
            get
            {
                return this.characteristicsField;
            }
            set
            {
                this.characteristicsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string EAN
        {
            get
            {
                return this.eANField;
            }
            set
            {
                this.eANField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.hotel-manager.org")]
    public partial class Unit
    {
        
        private string idField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.hotel-manager.org")]
    public partial class Store
    {
        
        private string idField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.hotel-manager.org")]
    public partial class StoresList
    {
        
        private Store[] dataField;
        
        private string errorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("data", Order=0)]
        public Store[] data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string error
        {
            get
            {
                return this.errorField;
            }
            set
            {
                this.errorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.hotel-manager.org")]
    public partial class ProductSale
    {
        
        private string productIdField;
        
        private float quantityField;
        
        private float priceField;
        
        private Unit unitField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ProductId
        {
            get
            {
                return this.productIdField;
            }
            set
            {
                this.productIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public float Quantity
        {
            get
            {
                return this.quantityField;
            }
            set
            {
                this.quantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public float Price
        {
            get
            {
                return this.priceField;
            }
            set
            {
                this.priceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public Unit Unit
        {
            get
            {
                return this.unitField;
            }
            set
            {
                this.unitField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.hotel-manager.org")]
    public partial class Sale
    {
        
        private string idField;
        
        private string organizationIdField;
        
        private string clientIdField;
        
        private string storeIdField;
        
        private string userIdField;
        
        private ProductSale[] productSalesField;
        
        private System.Nullable<System.DateTime> dateField;
        
        private string commentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string OrganizationId
        {
            get
            {
                return this.organizationIdField;
            }
            set
            {
                this.organizationIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string ClientId
        {
            get
            {
                return this.clientIdField;
            }
            set
            {
                this.clientIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string StoreId
        {
            get
            {
                return this.storeIdField;
            }
            set
            {
                this.storeIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string UserId
        {
            get
            {
                return this.userIdField;
            }
            set
            {
                this.userIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ProductSales", Order=5)]
        public ProductSale[] ProductSales
        {
            get
            {
                return this.productSalesField;
            }
            set
            {
                this.productSalesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public System.Nullable<System.DateTime> Date
        {
            get
            {
                return this.dateField;
            }
            set
            {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string Comment
        {
            get
            {
                return this.commentField;
            }
            set
            {
                this.commentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.hotel-manager.org")]
    public partial class SalesList
    {
        
        private Sale[] dataField;
        
        private string errorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("data", Order=0)]
        public Sale[] data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string error
        {
            get
            {
                return this.errorField;
            }
            set
            {
                this.errorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.hotel-manager.org")]
    public partial class Organization
    {
        
        private string idField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.hotel-manager.org")]
    public partial class OrganizationsList
    {
        
        private Organization[] dataField;
        
        private string errorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("data", Order=0)]
        public Organization[] data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string error
        {
            get
            {
                return this.errorField;
            }
            set
            {
                this.errorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.hotel-manager.org")]
    public partial class UserSettings
    {
        
        private string userIDField;
        
        private string defaultOrganizationIdField;
        
        private string defaultStoreIdField;
        
        private string defaultMoneyStoreIdField;
        
        private string errorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UserID
        {
            get
            {
                return this.userIDField;
            }
            set
            {
                this.userIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string DefaultOrganizationId
        {
            get
            {
                return this.defaultOrganizationIdField;
            }
            set
            {
                this.defaultOrganizationIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string DefaultStoreId
        {
            get
            {
                return this.defaultStoreIdField;
            }
            set
            {
                this.defaultStoreIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string DefaultMoneyStoreId
        {
            get
            {
                return this.defaultMoneyStoreIdField;
            }
            set
            {
                this.defaultMoneyStoreIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string error
        {
            get
            {
                return this.errorField;
            }
            set
            {
                this.errorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.hotel-manager.org")]
    public partial class MoneyStore
    {
        
        private string idField;
        
        private string nameField;
        
        private string organizationIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string OrganizationId
        {
            get
            {
                return this.organizationIdField;
            }
            set
            {
                this.organizationIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.hotel-manager.org")]
    public partial class MoneyStoresList
    {
        
        private MoneyStore[] dataField;
        
        private string errorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("data", Order=0)]
        public MoneyStore[] data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string error
        {
            get
            {
                return this.errorField;
            }
            set
            {
                this.errorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.hotel-manager.org")]
    public partial class Characteristic
    {
        
        private string idField;
        
        private string nameField;
        
        private System.Nullable<float> priceField;
        
        private string eANField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<float> Price
        {
            get
            {
                return this.priceField;
            }
            set
            {
                this.priceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string EAN
        {
            get
            {
                return this.eANField;
            }
            set
            {
                this.eANField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getProducts", WrapperNamespace="HotelManager", IsWrapped=true)]
    public partial class getProductsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="HotelManager", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string productID;
        
        public getProductsRequest()
        {
        }
        
        public getProductsRequest(string productID)
        {
            this.productID = productID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getProductsResponse", WrapperNamespace="HotelManager", IsWrapped=true)]
    public partial class getProductsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="HotelManager", Order=0)]
        public HotelManager.ProductsList @return;
        
        public getProductsResponse()
        {
        }
        
        public getProductsResponse(HotelManager.ProductsList @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getMoneyStoresList", WrapperNamespace="HotelManager", IsWrapped=true)]
    public partial class getMoneyStoresListRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="HotelManager", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string moneyStoreID;
        
        public getMoneyStoresListRequest()
        {
        }
        
        public getMoneyStoresListRequest(string moneyStoreID)
        {
            this.moneyStoreID = moneyStoreID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getMoneyStoresListResponse", WrapperNamespace="HotelManager", IsWrapped=true)]
    public partial class getMoneyStoresListResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="HotelManager", Order=0)]
        public HotelManager.MoneyStoresList @return;
        
        public getMoneyStoresListResponse()
        {
        }
        
        public getMoneyStoresListResponse(HotelManager.MoneyStoresList @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getUserSettings", WrapperNamespace="HotelManager", IsWrapped=true)]
    public partial class getUserSettingsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="HotelManager", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userName;
        
        public getUserSettingsRequest()
        {
        }
        
        public getUserSettingsRequest(string userName)
        {
            this.userName = userName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getUserSettingsResponse", WrapperNamespace="HotelManager", IsWrapped=true)]
    public partial class getUserSettingsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="HotelManager", Order=0)]
        public HotelManager.UserSettings @return;
        
        public getUserSettingsResponse()
        {
        }
        
        public getUserSettingsResponse(HotelManager.UserSettings @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getOrganizationsList", WrapperNamespace="HotelManager", IsWrapped=true)]
    public partial class getOrganizationsListRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="HotelManager", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string organizationID;
        
        public getOrganizationsListRequest()
        {
        }
        
        public getOrganizationsListRequest(string organizationID)
        {
            this.organizationID = organizationID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getOrganizationsListResponse", WrapperNamespace="HotelManager", IsWrapped=true)]
    public partial class getOrganizationsListResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="HotelManager", Order=0)]
        public HotelManager.OrganizationsList @return;
        
        public getOrganizationsListResponse()
        {
        }
        
        public getOrganizationsListResponse(HotelManager.OrganizationsList @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getStoresList", WrapperNamespace="HotelManager", IsWrapped=true)]
    public partial class getStoresListRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="HotelManager", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string storeID;
        
        public getStoresListRequest()
        {
        }
        
        public getStoresListRequest(string storeID)
        {
            this.storeID = storeID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getStoresListResponse", WrapperNamespace="HotelManager", IsWrapped=true)]
    public partial class getStoresListResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="HotelManager", Order=0)]
        public HotelManager.StoresList @return;
        
        public getStoresListResponse()
        {
        }
        
        public getStoresListResponse(HotelManager.StoresList @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface HotelManagerPortTypeChannel : HotelManager.HotelManagerPortType, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class HotelManagerPortTypeClient : System.ServiceModel.ClientBase<HotelManager.HotelManagerPortType>, HotelManager.HotelManagerPortType
    {
        
        /// <summary>
        /// Реализуйте этот разделяемый метод для настройки конечной точки службы.
        /// </summary>
        /// <param name="serviceEndpoint">Настраиваемая конечная точка</param>
        /// <param name="clientCredentials">Учетные данные клиента.</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public HotelManagerPortTypeClient(EndpointConfiguration endpointConfiguration) : 
                base(HotelManagerPortTypeClient.GetBindingForEndpoint(endpointConfiguration), HotelManagerPortTypeClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public HotelManagerPortTypeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(HotelManagerPortTypeClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public HotelManagerPortTypeClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(HotelManagerPortTypeClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public HotelManagerPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public string getHello()
        {
            return base.Channel.getHello();
        }
        
        public System.Threading.Tasks.Task<string> getHelloAsync()
        {
            return base.Channel.getHelloAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HotelManager.getProductsResponse HotelManager.HotelManagerPortType.getProducts(HotelManager.getProductsRequest request)
        {
            return base.Channel.getProducts(request);
        }
        
        public HotelManager.ProductsList getProducts(string productID)
        {
            HotelManager.getProductsRequest inValue = new HotelManager.getProductsRequest();
            inValue.productID = productID;
            HotelManager.getProductsResponse retVal = ((HotelManager.HotelManagerPortType)(this)).getProducts(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HotelManager.getProductsResponse> HotelManager.HotelManagerPortType.getProductsAsync(HotelManager.getProductsRequest request)
        {
            return base.Channel.getProductsAsync(request);
        }
        
        public System.Threading.Tasks.Task<HotelManager.getProductsResponse> getProductsAsync(string productID)
        {
            HotelManager.getProductsRequest inValue = new HotelManager.getProductsRequest();
            inValue.productID = productID;
            return ((HotelManager.HotelManagerPortType)(this)).getProductsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HotelManager.getMoneyStoresListResponse HotelManager.HotelManagerPortType.getMoneyStoresList(HotelManager.getMoneyStoresListRequest request)
        {
            return base.Channel.getMoneyStoresList(request);
        }
        
        public HotelManager.MoneyStoresList getMoneyStoresList(string moneyStoreID)
        {
            HotelManager.getMoneyStoresListRequest inValue = new HotelManager.getMoneyStoresListRequest();
            inValue.moneyStoreID = moneyStoreID;
            HotelManager.getMoneyStoresListResponse retVal = ((HotelManager.HotelManagerPortType)(this)).getMoneyStoresList(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HotelManager.getMoneyStoresListResponse> HotelManager.HotelManagerPortType.getMoneyStoresListAsync(HotelManager.getMoneyStoresListRequest request)
        {
            return base.Channel.getMoneyStoresListAsync(request);
        }
        
        public System.Threading.Tasks.Task<HotelManager.getMoneyStoresListResponse> getMoneyStoresListAsync(string moneyStoreID)
        {
            HotelManager.getMoneyStoresListRequest inValue = new HotelManager.getMoneyStoresListRequest();
            inValue.moneyStoreID = moneyStoreID;
            return ((HotelManager.HotelManagerPortType)(this)).getMoneyStoresListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HotelManager.getUserSettingsResponse HotelManager.HotelManagerPortType.getUserSettings(HotelManager.getUserSettingsRequest request)
        {
            return base.Channel.getUserSettings(request);
        }
        
        public HotelManager.UserSettings getUserSettings(string userName)
        {
            HotelManager.getUserSettingsRequest inValue = new HotelManager.getUserSettingsRequest();
            inValue.userName = userName;
            HotelManager.getUserSettingsResponse retVal = ((HotelManager.HotelManagerPortType)(this)).getUserSettings(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HotelManager.getUserSettingsResponse> HotelManager.HotelManagerPortType.getUserSettingsAsync(HotelManager.getUserSettingsRequest request)
        {
            return base.Channel.getUserSettingsAsync(request);
        }
        
        public System.Threading.Tasks.Task<HotelManager.getUserSettingsResponse> getUserSettingsAsync(string userName)
        {
            HotelManager.getUserSettingsRequest inValue = new HotelManager.getUserSettingsRequest();
            inValue.userName = userName;
            return ((HotelManager.HotelManagerPortType)(this)).getUserSettingsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HotelManager.getOrganizationsListResponse HotelManager.HotelManagerPortType.getOrganizationsList(HotelManager.getOrganizationsListRequest request)
        {
            return base.Channel.getOrganizationsList(request);
        }
        
        public HotelManager.OrganizationsList getOrganizationsList(string organizationID)
        {
            HotelManager.getOrganizationsListRequest inValue = new HotelManager.getOrganizationsListRequest();
            inValue.organizationID = organizationID;
            HotelManager.getOrganizationsListResponse retVal = ((HotelManager.HotelManagerPortType)(this)).getOrganizationsList(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HotelManager.getOrganizationsListResponse> HotelManager.HotelManagerPortType.getOrganizationsListAsync(HotelManager.getOrganizationsListRequest request)
        {
            return base.Channel.getOrganizationsListAsync(request);
        }
        
        public System.Threading.Tasks.Task<HotelManager.getOrganizationsListResponse> getOrganizationsListAsync(string organizationID)
        {
            HotelManager.getOrganizationsListRequest inValue = new HotelManager.getOrganizationsListRequest();
            inValue.organizationID = organizationID;
            return ((HotelManager.HotelManagerPortType)(this)).getOrganizationsListAsync(inValue);
        }
        
        public HotelManager.SalesList getSales()
        {
            return base.Channel.getSales();
        }
        
        public System.Threading.Tasks.Task<HotelManager.SalesList> getSalesAsync()
        {
            return base.Channel.getSalesAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HotelManager.getStoresListResponse HotelManager.HotelManagerPortType.getStoresList(HotelManager.getStoresListRequest request)
        {
            return base.Channel.getStoresList(request);
        }
        
        public HotelManager.StoresList getStoresList(string storeID)
        {
            HotelManager.getStoresListRequest inValue = new HotelManager.getStoresListRequest();
            inValue.storeID = storeID;
            HotelManager.getStoresListResponse retVal = ((HotelManager.HotelManagerPortType)(this)).getStoresList(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HotelManager.getStoresListResponse> HotelManager.HotelManagerPortType.getStoresListAsync(HotelManager.getStoresListRequest request)
        {
            return base.Channel.getStoresListAsync(request);
        }
        
        public System.Threading.Tasks.Task<HotelManager.getStoresListResponse> getStoresListAsync(string storeID)
        {
            HotelManager.getStoresListRequest inValue = new HotelManager.getStoresListRequest();
            inValue.storeID = storeID;
            return ((HotelManager.HotelManagerPortType)(this)).getStoresListAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.HotelManagerSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.HotelManagerSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Не удалось найти конечную точку с именем \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.HotelManagerSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://192.168.1.152/ApartmentDeveloper/ws/ws2.1cws");
            }
            if ((endpointConfiguration == EndpointConfiguration.HotelManagerSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://192.168.1.152/ApartmentDeveloper/ws/ws2.1cws");
            }
            throw new System.InvalidOperationException(string.Format("Не удалось найти конечную точку с именем \"{0}\".", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            HotelManagerSoap,
            
            HotelManagerSoap12,
        }
    }
}
